### ISSUE TITLE
qui-picker组件问题

### ISSUE THREAD

**Issue by wsj2012** [qapp-ui/qapp-ui#1]
你好，qui-picker组件在华为手机上运行存在问题，存在crash问题以及UI显示问题，麻烦看下，希望能兼容华为手机厂商的设备。多谢。。。

**Comment by shenzhim** [comment]
多谢反馈，麻烦提供下华为手机型号以及快应用版本信息

**Comment by wsj2012** [comment]
华为P9，华为快应用加载器最新版本（1.0.3.301）。

**Comment by shenzhim** [comment]
适配华为手机引擎问题，我们已经修复，并提交了change。
再次感谢反馈的问题
