### ISSUE TITLE
部分组件在华为上存在兼容性问题

### ISSUE THREAD

**Issue by powerjsns** [qapp-ui/qapp-ui#2]
发现在华为手机上，部分组件（button，popup等）存在兼容性问题

**Comment by shenzhim** [comment]
谢谢反馈，在华为手机上的兼容问题，我们已经发现，目前正在解决兼容性问题。
解决后，我们会在第一时间修复。

**Comment by shenzhim** [comment]
华为手机的适配问题，我们已经修复，并提交了change。
再次感谢问题的反馈
