### ISSUE TITLE
提示文件不存在

### ISSUE THREAD

**Issue by magic007** [qapp-ui/qapp-ui#3]
ERROR: import 文件不存在，filepath : /Users/xxx/Applications/web/work/hap/qapp-ui/src/Action/@qapp-ui/qui-action/index
 @

**Comment by shenzhim** [comment]
可以通过在项目根目录新建config目录创建webpack.config.js文件来修改hap-toolkit工具中默认的webpack配置信息，来增加alias的设置

可看下README.md中的注意点 说明
https://github.com/qapp-ui/qapp-ui#%E6%B3%A8%E6%84%8F%E7%82%B9

**Comment by magic007** [comment]
是的，我改了这里。可是华为开发工具根本没用。http://developer.huawei.com/consumer/cn/service/hms/catalog/fastapp.html?page=fastapp_fastapp_devprepare_install_tool   你可以试试。

**Comment by shenzhim** [comment]
非常感谢反馈的问题。

使用华为ide的话 打包编译时是会报错的，原因在于华为ide还不支持alias的设置。

有两种方式解决你的问题
1. 如果需要使用华为ide来进行打包编译的话，不建议使用别名的方式引入文件
2. 可以通过快应用的hap-toolkit工具进行打包编译，打包编译后的rpk包同样可以在华为引擎上执行的。

**Comment by magic007** [comment]
好的，也感谢提供这个框架。 我暂时写了相对路径，完美。  我觉得里面组件都偏大，像列表，搜索都是，建议可以缩下一号。  

我基于这个写了个前端商城UI，需要可以下载试试。https://github.com/bmob/quick-shop
